name: Node.js CI/CD with Blue/Green Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip application
      run: |
        zip -r ../app.zip .
      working-directory: app

    - name: Upload to S3
      run: |
        aws s3 cp ../app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app.zip

    - name: Create CodeDeploy Deployment
      run: |
        aws deploy create-deployment \
          --application-name asg-rollout-app \
          --deployment-group-name asg-rollout-deployment-group \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=app.zip,bundleType=zip
